### ISSUE TITLE
Unassign failed

### ISSUE THREAD

**Issue by lazyatom** [freerange/harmonia-old#8]
```
/home/harmonia/apps/harmonia/lib/harmonia/administrator.rb:29:in `unassign': undefined method `delete' for false:FalseClass (NoMethodError)
    from /home/harmonia/apps/harmonia/lib/harmonia.rb:27:in `unassign'
    from -e:1:in `<main>'
```

**Comment by lazyatom** [comment]
This should be fixed in af93335. The problem occurred when the YAML store file was an empty file, such that `YAML.load_file` returned false.
